using System;

#nullable disable

namespace DataAccessLayer.Entities.AvroraWMS
{
    public partial class IcsarticleOnline
    {
        public int ActionTypeStatic { get; set; }
        public int StockCodeStatic { get; set; }
        public int DepotCodeStatic { get; set; }
        public int OwnerStockCodeStatic { get; set; }
        public string ProdId { get; set; }
        public int ArticleLogisticVersionStatic { get; set; }
        public int LogisticVersionCodeStatic { get; set; }
        public int ArticleTypeStatic { get; set; }
        public string CompId { get; set; }
        public string CompName { get; set; }
        public string ProdName { get; set; }
        public string BarCode { get; set; }
        public int BarCodeTransferCodeStatic { get; set; }
        public int BarCodeTypeStatic { get; set; }
        public int? ExpirationDateStatic { get; set; }
        public int? ExpirationDateOnProviderStatic { get; set; }
        public int? ExpirationDateOnStockStatic { get; set; }
        public int? ExpirationDateOnShopStatic { get; set; }
        public int? ExpirationDateOnCustomerStatic { get; set; }
        public int? ExpirationDateUnitTypeStatic { get; set; }
        public string PcatId { get; set; }
        public string PcatName { get; set; }
        public string PgrId { get; set; }
        public string PgrName { get; set; }
        public string PgrId1 { get; set; }
        public string Pgr1Name { get; set; }
        public string PgrId2 { get; set; }
        public string Pgr2Name { get; set; }
        public int? PgrId3Static { get; set; }
        public int? Pgr3NameStatic { get; set; }
        public int? PgrId4Static { get; set; }
        public int? Pgr4NameStatic { get; set; }
        public int? IarpnetunitCodeStatic { get; set; }
        public int? IarpnetunitTypeStatic { get; set; }
        public int? CapacityValueStatic { get; set; }
        public int SamplingUnitCodeStatic { get; set; }
        public int SaleUnitStatic { get; set; }
        public int? UnitQtyInsubBox { get; set; }
        public int? UnitQtyInbox { get; set; }
        public int? BoxQtyOnRow { get; set; }
        public int? BoxRowsOnPallet { get; set; }
        public int IndicatorInStickerAreaStatic { get; set; }
        public int TagFormatStatic { get; set; }
        public int ItemManagementTypeStatic { get; set; }
        public decimal SellingPriceAfterTaxStatic { get; set; }
        public int? WeightUnitStatic { get; set; }
        public int? LengthUnitStatic { get; set; }
        public int? SpaceUnitStatic { get; set; }
        public decimal? UnitLengthCm { get; set; }
        public decimal? UnitWidthCm { get; set; }
        public decimal? UnitHeightCm { get; set; }
        public decimal? UnitGrossWeightKg { get; set; }
        public decimal? SubBoxLengthCm { get; set; }
        public decimal? SubBoxWidthCm { get; set; }
        public decimal? SubBoxHeightCm { get; set; }
        public decimal? SubBoxWeightKg { get; set; }
        public decimal? BoxLengthCm { get; set; }
        public decimal? BoxWidthCm { get; set; }
        public decimal? BoxHeightCm { get; set; }
        public decimal? BoxWeightKg { get; set; }
        public decimal? LayerLengthCm { get; set; }
        public decimal? LayerWidthCm { get; set; }
        public decimal? LayerHeightCm { get; set; }
        public decimal? LayerWeightKg { get; set; }
        public decimal? PalletLengthCm { get; set; }
        public decimal? PalletWidthCm { get; set; }
        public decimal? PalletHeightCm { get; set; }
        public decimal? PalletGrossWeightKg { get; set; }
        public int? Iarupuvc { get; set; }
        public int? Iarupspc { get; set; }
        public int? Iaruppcb { get; set; }
        public int? Iarupcou { get; set; }
        public int? Iaruppal { get; set; }
        public int? Iartmax { get; set; }
        public int? Iartmin { get; set; }
        public int? Iardang { get; set; }
        public int? Iarcero { get; set; }
        public int? Iarcerc { get; set; }
        public int? Iarcers { get; set; }
        public int? Iariger { get; set; }
        public int? Iarpger { get; set; }
        public int? Iartsit { get; set; }
        public int? Iarpent { get; set; }
        public int? Iarppv { get; set; }
        public int Iarperm { get; set; }
        public int? Iarralc { get; set; }
        public int? Iarcalc { get; set; }
        public int? Iardegr { get; set; }
        public int? Iarcreg { get; set; }
        public int? Iarcvin { get; set; }
        public int? Iarpori { get; set; }
        public int? Iarintemb { get; set; }
        public int? Iareuvc { get; set; }
        public int? Iarespcb { get; set; }
        public int? Iarepcb { get; set; }
        public int? Iarecou { get; set; }
        public int? Iarepal { get; set; }
        public int? Iareinter { get; set; }
        public DateTime Iardcre { get; set; }
        public DateTime? Iardmaj { get; set; }
        public string Iarutil { get; set; }
        public string Iarnlis { get; set; }
        public int? Iartypul { get; set; }
        public int? Iareancde { get; set; }
        public int? Iarndouan { get; set; }
        public int? Iarsuivemb { get; set; }
        public int? Iartypeemb { get; set; }
        public int? Iarcnuflou { get; set; }
        public int? Iarcont { get; set; }
        public int? Iarucont { get; set; }
        public int? Iartucont { get; set; }
        public int? Iarugest { get; set; }
        public int? Iarfspcb { get; set; }
        public int? Iarfpcb { get; set; }
        public int? Iarfcarc { get; set; }
        public int? Iarfcpal { get; set; }
        public int? Iargescon { get; set; }
        public int? Iarcexv { get; set; }
        public bool? TrackWms { get; set; }
        public bool? ActiveAssortment { get; set; }
    }
}
