using System;

#nullable disable

namespace DataAccessLayer.Entities.AvroraWMS
{
    public partial class Icsdeol
    {
        public short Iolacti { get; set; }
        public int Iolcent { get; set; }
        public short Ioldepo { get; set; }
        public int? Iolsite { get; set; }
        public string Iolcexcde { get; set; }
        public int? Iolcincde { get; set; }
        public string Iolnolign { get; set; }
        public int? Iolnctl { get; set; }
        public short Ioltype { get; set; }
        public string Iolncli { get; set; }
        public string Iollibl { get; set; }
        public int? Iolfilc { get; set; }
        public DateTime Ioldliv { get; set; }
        public DateTime Ioldcom { get; set; }
        public short Iolimrl { get; set; }
        public short Iolnlig { get; set; }
        public string Iolcodc { get; set; }
        public short Iolcexvlc { get; set; }
        public string Iolcodp { get; set; }
        public short Iolcexvlp { get; set; }
        public int? Iolcoef { get; set; }
        public short Ioliurg { get; set; }
        public string Iollfon { get; set; }
        public string Iolrais { get; set; }
        public string Ioladr1 { get; set; }
        public string Ioladr2 { get; set; }
        public string Iolvill { get; set; }
        public string Iolcpos { get; set; }
        public string Ioldist { get; set; }
        public short? Iolcpay { get; set; }
        public string Iollpay { get; set; }
        public string Iolregn { get; set; }
        public string Iollcor { get; set; }
        public string Iolntel { get; set; }
        public string Iolnfax { get; set; }
        public string Iolntlx { get; set; }
        public string Iolmail { get; set; }
        public string Iolphostd { get; set; }
        public string Iolphodir { get; set; }
        public string Iolphomob { get; set; }
        public decimal Iolqtec { get; set; }
        public int? Iolqteip { get; set; }
        public int? Iolqtelp { get; set; }
        public decimal? Iolqtei { get; set; }
        public decimal? Iolpvttc { get; set; }
        public decimal? Iolpvht { get; set; }
        public decimal? Iolpcttc { get; set; }
        public decimal? Iolpcht { get; set; }
        public decimal? Iolttva { get; set; }
        public int? Iolnooe { get; set; }
        public string Iolcnuf { get; set; }
        public string Iolccom { get; set; }
        public int? Iolfili { get; set; }
        public string Iolcexglo { get; set; }
        public string Iolclcus { get; set; }
        public int? Iolcus { get; set; }
        public string Iolaori { get; set; }
        public decimal? Iolfrei { get; set; }
        public DateTime? Ioldplim { get; set; }
        public DateTime? Ioldelim { get; set; }
        public DateTime? Ioldlim { get; set; }
        public short? Ioluint { get; set; }
        public short? Iolupre { get; set; }
        public short? Iolcuex { get; set; }
        public short? Iolaslo { get; set; }
        public string Iolnliv { get; set; }
        public string Iolngrp { get; set; }
        public string Iolplet { get; set; }
        public string Ioltypr { get; set; }
        public short? Iolpenu { get; set; }
        public string Ioliebl { get; set; }
        public string Iollibbl { get; set; }
        public string Iolnflu { get; set; }
        public string Ioliflu { get; set; }
        public string Iolnacc { get; set; }
        public string Ioliacc { get; set; }
        public decimal? Iolmarg { get; set; }
        public decimal? Ioldmar { get; set; }
        public string Iolcdev { get; set; }
        public short? Iolctva { get; set; }
        public string Iolcfam { get; set; }
        public short? Ioliedf { get; set; }
        public short? Iolicmp { get; set; }
        public short? Iolitce { get; set; }
        public string Iolcfxf { get; set; }
        public string Iolcset { get; set; }
        public string Iolclet { get; set; }
        public DateTime? Ioldcre { get; set; }
        public DateTime? Ioldmaj { get; set; }
        public string Iolutil { get; set; }
        public string Iolrefcde { get; set; }
        public string Iolacci { get; set; }
        public string Iolbudcode { get; set; }
        public int? Iolnops { get; set; }
        public int? Iolnligp { get; set; }
        public short Iolflgmut { get; set; }
        public string Iolcexops { get; set; }
        public short? Iolflgtrc { get; set; }
        public string Iolidcmp { get; set; }
        public string Ioltrsp { get; set; }
        public int? Iolcrgp { get; set; }
        public short? Iolflir { get; set; }
        public short? Iolnolv { get; set; }
        public int? Iolcinbv { get; set; }
        public string Iolcsmcext { get; set; }
        public string Iolcsnn { get; set; }
        public string Iolcsnp { get; set; }
        public short? Iolvtliv { get; set; }
        public string Ioltrcnum { get; set; }
        public int? Ioltrfil { get; set; }
        public short? Ioledtfac { get; set; }
        public int? Iolmodtno { get; set; }
        public int? Ioltret { get; set; }
        public int? Iolprif { get; set; }
        public string Iolcomm { get; set; }
        public int? Iolstowith { get; set; }
        public int? Iolgancode { get; set; }
        public int? Iolcargrp { get; set; }
        public int? Ioldelpt1 { get; set; }
        public int? Ioldelpt1lfon { get; set; }
        public int? Ioldelpt1rais { get; set; }
        public int? Ioldelpt1adr1 { get; set; }
        public int? Ioldelpt1adr2 { get; set; }
        public int? Ioldelpt1vill { get; set; }
        public int? Ioldelpt1cpos { get; set; }
        public int? Ioldelpt1dist { get; set; }
        public int? Ioldelpt1cpay { get; set; }
        public int? Ioldelpt1lpay { get; set; }
        public int? Ioldelpt1regn { get; set; }
        public int? Ioldelpt1lcor { get; set; }
        public int? Ioldelpt1ntel { get; set; }
        public int? Ioldelpt1nfax { get; set; }
        public int? Ioldelpt1ntlx { get; set; }
        public int? Ioldelpt1mail { get; set; }
        public int? Ioldelpt2 { get; set; }
        public int? Ioldelpt2lfon { get; set; }
        public int? Ioldelpt2rais { get; set; }
        public int? Ioldelpt2adr1 { get; set; }
        public int? Ioldelpt2adr2 { get; set; }
        public int? Ioldelpt2vill { get; set; }
        public int? Ioldelpt2cpos { get; set; }
        public int? Ioldelpt2dist { get; set; }
        public int? Ioldelpt2cpay { get; set; }
        public int? Ioldelpt2lpay { get; set; }
        public int? Ioldelpt2regn { get; set; }
        public int? Ioldelpt2lcor { get; set; }
        public int? Ioldelpt2ntel { get; set; }
        public int? Ioldelpt2nfax { get; set; }
        public int? Ioldelpt2ntlx { get; set; }
        public int? Ioldelpt2mail { get; set; }
        public int? Ioldgrpfor { get; set; }
        public int? Iolgrpforlfon { get; set; }
        public int? Iolgrpforrais { get; set; }
        public int? Iolgrpforadr1 { get; set; }
        public int? Iolgrpforadr2 { get; set; }
        public int? Iolgrpforvill { get; set; }
        public int? Iolgrpforcpos { get; set; }
        public int? Iolgrpfordist { get; set; }
        public int? Iolgrpforcpay { get; set; }
        public int? Iolgrpforlpay { get; set; }
        public int? Iolgrpforregn { get; set; }
        public int? Iolgrpforlcor { get; set; }
        public int? Iolgrpforntel { get; set; }
        public int? Iolgrpfornfax { get; set; }
        public int? Iolgrpforntlx { get; set; }
        public int? Iolgrpformail { get; set; }
        public DateTime? Ioldlvmin { get; set; }
        public DateTime? Ioldlvmax { get; set; }
        public string Ioloptin1 { get; set; }
        public string Ioltypin1 { get; set; }
        public string Iolvalin1 { get; set; }
        public string Ioloptin2 { get; set; }
        public string Ioltypin2 { get; set; }
        public string Iolvalin2 { get; set; }
        public string Ioloptin3 { get; set; }
        public string Ioltypin3 { get; set; }
        public string Iolvalin3 { get; set; }
        public string Ioloptin4 { get; set; }
        public string Ioltypin4 { get; set; }
        public string Iolvalin4 { get; set; }
        public string Ioloptin5 { get; set; }
        public string Ioltypin5 { get; set; }
        public string Iolvalin5 { get; set; }
    }
}
